function createfigureForFreyFace(cdata1, cdata2, cdata3, cdata4, cdata5, cdata6, cdata7, cdata8, cdata9, cdata10, cdata11, cdata12, cdata13, cdata14, cdata15, cdata16, cdata17, cdata18, cdata19, cdata20, cdata21, cdata22, cdata23, cdata24, cdata25, cdata26, cdata27, cdata28, cdata29, cdata30, cdata31, cdata32, cdata33, cdata34, cdata35, cdata36, cdata37, cdata38, cdata39, cdata40, cdata41, cdata42)
%CREATEFIGURE(CDATA1,CDATA2,CDATA3,CDATA4,CDATA5,CDATA6,CDATA7,CDATA8,CDATA9,CDATA10,CDATA11,CDATA12,CDATA13,CDATA14,CDATA15,CDATA16,CDATA17,CDATA18,CDATA19,CDATA20,CDATA21,CDATA22,CDATA23,CDATA24,CDATA25,CDATA26,CDATA27,CDATA28,CDATA29,CDATA30,CDATA31,CDATA32,CDATA33,CDATA34,CDATA35,CDATA36,CDATA37,CDATA38,CDATA39,CDATA40,CDATA41,CDATA42)
%  CDATA1:  image cdata
%  CDATA2:  image cdata
%  CDATA3:  image cdata
%  CDATA4:  image cdata
%  CDATA5:  image cdata
%  CDATA6:  image cdata
%  CDATA7:  image cdata
%  CDATA8:  image cdata
%  CDATA9:  image cdata
%  CDATA10:  image cdata
%  CDATA11:  image cdata
%  CDATA12:  image cdata
%  CDATA13:  image cdata
%  CDATA14:  image cdata
%  CDATA15:  image cdata
%  CDATA16:  image cdata
%  CDATA17:  image cdata
%  CDATA18:  image cdata
%  CDATA19:  image cdata
%  CDATA20:  image cdata
%  CDATA21:  image cdata
%  CDATA22:  image cdata
%  CDATA23:  image cdata
%  CDATA24:  image cdata
%  CDATA25:  image cdata
%  CDATA26:  image cdata
%  CDATA27:  image cdata
%  CDATA28:  image cdata
%  CDATA29:  image cdata
%  CDATA30:  image cdata
%  CDATA31:  image cdata
%  CDATA32:  image cdata
%  CDATA33:  image cdata
%  CDATA34:  image cdata
%  CDATA35:  image cdata
%  CDATA36:  image cdata
%  CDATA37:  image cdata
%  CDATA38:  image cdata
%  CDATA39:  image cdata
%  CDATA40:  image cdata
%  CDATA41:  image cdata
%  CDATA42:  image cdata

%  Auto-generated by MATLAB on 15-Dec-2011 22:36:12

% Create figure
figure1 = figure;
colormap('gray');

% Create axes
axes1 = axes('Parent',figure1,'ZColor',[1 0 0],'YTick',zeros(1,0),...
    'YDir','reverse',...
    'YColor',[1 0 0],...
    'XColor',[1 0 0],...
    'Position',[0.350418410041835 -0.00452488687782803 0.0627615062761469 1.00226244343891],...
    'Layer','top');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.0157894736842105 0.615789473684211]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.0155555555555556 10.9355555555556]);
box(axes1,'on');
hold(axes1,'all');

% Create image
image([0 0.6],[0 0.84],cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create image
image([0 0.6],[0.84 1.68],cdata2,'Parent',axes1,'CDataMapping','scaled');

% Create image
image([0 0.6],[1.68 2.52],cdata3,'Parent',axes1,'CDataMapping','scaled');

% Create image
image([0 0.6],[2.52 3.36],cdata4,'Parent',axes1,'CDataMapping','scaled');

% Create image
image([0 0.6],[3.36 4.2],cdata5,'Parent',axes1,'CDataMapping','scaled');

% Create image
image([0 0.6],[4.2 5.04],cdata6,'Parent',axes1,'CDataMapping','scaled');

% Create image
image([0 0.6],[5.04 5.88],cdata7,'Parent',axes1,'CDataMapping','scaled');

% Create image
image([0 0.6],[5.88 6.72],cdata8,'Parent',axes1,'CDataMapping','scaled');

% Create image
image([0 0.6],[6.72 7.56],cdata9,'Parent',axes1,'CDataMapping','scaled');

% Create image
image([0 0.6],[7.56 8.4],cdata10,'Parent',axes1,'CDataMapping','scaled');

% Create image
image([0 0.6],[8.4 9.24],cdata11,'Parent',axes1,'CDataMapping','scaled');

% Create image
image([0 0.6],[9.24 10.08],cdata12,'Parent',axes1,'CDataMapping','scaled');

% Create image
image([0 0.6],[10.08 10.92],cdata13,'Parent',axes1,'CDataMapping','scaled');

% Create axes
axes2 = axes('Parent',figure1,'ZColor',[0 0 1],'YTick',zeros(1,0),...
    'YDir','reverse',...
    'YColor',[0 0 1],...
    'XColor',[0 0 1],...
    'Position',[0.437238493723847 0.00226244343891403 0.0638075313807533 0.995475113122174],...
    'Layer','top');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[-0.0157894736842105 0.615789473684211]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[-0.0155555555555556 11.7755555555556]);
box(axes2,'on');
hold(axes2,'all');

% Create image
image([0 0.6],[0 0.84],cdata14,'Parent',axes2,'CDataMapping','scaled');

% Create image
image([0 0.6],[0.84 1.68],cdata15,'Parent',axes2,'CDataMapping','scaled');

% Create image
image([0 0.6],[1.68 2.52],cdata16,'Parent',axes2,'CDataMapping','scaled');

% Create image
image([0 0.6],[2.52 3.36],cdata17,'Parent',axes2,'CDataMapping','scaled');

% Create image
image([0 0.6],[3.36 4.2],cdata18,'Parent',axes2,'CDataMapping','scaled');

% Create image
image([0 0.6],[4.2 5.04],cdata19,'Parent',axes2,'CDataMapping','scaled');

% Create image
image([0 0.6],[5.04 5.88],cdata20,'Parent',axes2,'CDataMapping','scaled');

% Create image
image([0 0.6],[5.88 6.72],cdata21,'Parent',axes2,'CDataMapping','scaled');

% Create image
image([0 0.6],[6.72 7.56],cdata22,'Parent',axes2,'CDataMapping','scaled');

% Create image
image([0 0.6],[7.56 8.4],cdata23,'Parent',axes2,'CDataMapping','scaled');

% Create image
image([0 0.6],[8.4 9.24],cdata24,'Parent',axes2,'CDataMapping','scaled');

% Create image
image([0 0.6],[9.24 10.08],cdata25,'Parent',axes2,'CDataMapping','scaled');

% Create image
image([0 0.6],[10.08 10.92],cdata26,'Parent',axes2,'CDataMapping','scaled');

% Create image
image([0 0.6],[10.92 11.76],cdata27,'Parent',axes2,'CDataMapping','scaled');

% Create axes
axes3 = axes('Parent',figure1,'ZColor',[0 1 0],'YTick',zeros(1,0),...
    'YDir','reverse',...
    'YColor',[0 1 0],...
    'XColor',[0 1 0],...
    'Position',[0.523012552301235 0 0.0554393305439518 0.997737556561109],...
    'Layer','top');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[-0.0157894736842105 0.615789473684211]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[-0.0155555555555556 12.6155555555556]);
box(axes3,'on');
hold(axes3,'all');

% Create image
image([0 0.6],[0 0.84],cdata28,'Parent',axes3,'CDataMapping','scaled');

% Create image
image([0 0.6],[0.84 1.68],cdata29,'Parent',axes3,'CDataMapping','scaled');

% Create image
image([0 0.6],[1.68 2.52],cdata30,'Parent',axes3,'CDataMapping','scaled');

% Create image
image([0 0.6],[2.52 3.36],cdata31,'Parent',axes3,'CDataMapping','scaled');

% Create image
image([0 0.6],[3.36 4.2],cdata32,'Parent',axes3,'CDataMapping','scaled');

% Create image
image([0 0.6],[4.2 5.04],cdata33,'Parent',axes3,'CDataMapping','scaled');

% Create image
image([0 0.6],[5.04 5.88],cdata34,'Parent',axes3,'CDataMapping','scaled');

% Create image
image([0 0.6],[5.88 6.72],cdata35,'Parent',axes3,'CDataMapping','scaled');

% Create image
image([0 0.6],[6.72 7.56],cdata36,'Parent',axes3,'CDataMapping','scaled');

% Create image
image([0 0.6],[7.56 8.4],cdata37,'Parent',axes3,'CDataMapping','scaled');

% Create image
image([0 0.6],[8.4 9.24],cdata38,'Parent',axes3,'CDataMapping','scaled');

% Create image
image([0 0.6],[9.24 10.08],cdata39,'Parent',axes3,'CDataMapping','scaled');

% Create image
image([0 0.6],[10.08 10.92],cdata40,'Parent',axes3,'CDataMapping','scaled');

% Create image
image([0 0.6],[10.92 11.76],cdata41,'Parent',axes3,'CDataMapping','scaled');

% Create image
image([0 0.6],[11.76 12.6],cdata42,'Parent',axes3,'CDataMapping','scaled');

